<?php

if(!defined('BIENES_RAICES_FOLDER')) define('BIENES_RAICES_FOLDER','bienes_raices_fotos');

if(!defined('BIENES_RAICES_FOTOS_TMP_PATH')) define ('BIENES_RAICES_FOTOS_TMP_PATH', TMP.BIENES_RAICES_FOLDER.DS);

if(!defined('BIENES_RAICES_FOTOS_PATH')) define('BIENES_RAICES_FOTOS_PATH',IMAGES.BIENES_RAICES_FOLDER.DS);